### ISSUE TITLE
ArgoCD app syncs successfully with no svcs under any team

### ISSUE THREAD

**Issue by youngjeong46** [aws-quickstart/ssp-amazon-eks#1]
Following the [Deploying workloads with ArgoCD](https://github.com/aws-quickstart/quickstart-ssp-amazon-eks/blob/main/docs/argo.md) instructions, I was able to deploy workloads to the cluster and sync the apps successfully.

However, validation of deployments failed upon running the command

```
kubectl port-forward svc/guestbook-ui -n team-burnham 4040:80
```

Running kubectl commands revealed team-burnham, team-riker and team-troi in the namespaces, but none of those namespaces had anything in it.

**Comment by kcoleman731** [comment]
Issues has been resolved. Closing.
