### ISSUE TITLE
Document Observability

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#11]
We need to document how a customer can view logs / metrics etc via CloudWatch. Use cases 

1. View logs for my workload
2. View logs for my cluster 
3. View metrics for my workload
4. View metrics for my cluster 
5. View containers via that container map in container insights.

**Comment by parkand1** [comment]
Is this supposed to be different than the Container Insights documentation that was merged?

**Comment by kcoleman731** [comment]
Done https://github.com/aws-quickstart/ssp-amazon-eks/blob/main/docs/addons/container-insights.md
