### ISSUE TITLE
Add Velero addon to support backup and DR. 

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#125]
https://velero.io/

**Comment by shapirov103** [comment]
Backup and DR in the velero scope is handled by the platform ootb. We can provision another cluster in any region with all workloads from gitops. What is the use case?

**Comment by kcoleman731** [comment]
@shapirov103 persistent volumes...what Mike was talking about.

**Comment by shapirov103** [comment]
gotcha, then I suppose we should prioritize EBS CSI driver and EFS support.

**Comment by kcoleman731** [comment]
Covered in #143. Closing this ticket.
