### ISSUE TITLE
[FEATURE] - Add custom AMI for managed node groups

### ISSUE THREAD

**Issue by starchx** [aws-quickstart/ssp-amazon-eks#137]
Many organizations bake their own golden AMI and it is compulsory to use their AMI for EKS worker nodes. Custom AMI can be supported by implementing Launch Template for managed node groups.

**Comment by kcoleman731** [comment]
Looks like you will want to add a new property here? https://github.com/aws-quickstart/quickstart-ssp-amazon-eks/blob/main/lib/cluster-providers/ec2-cluster-provider.ts#L70 @starchx

**Comment by starchx** [comment]
Pretty much. The change will be in that ec2 provider, but adding Launch Template option to support custom AMI.

**Comment by starchx** [comment]
@shapirov103 @kcoleman731 I may not have permissions to add reviewers, can you help assign this PR? Thanks in advance :)
