### ISSUE TITLE
Add addon OPA Gatekeepr

### ISSUE THREAD

**Issue by starchx** [aws-quickstart/ssp-amazon-eks#141]
OPA Gatekeepr is often required in Enterprise K8s deployment to:
- apply preventative controls
- auditing
[Gatekeeper](https://github.com/open-policy-agent/gatekeeper)

**Comment by kcoleman731** [comment]
PR is in progress. https://github.com/aws-quickstart/ssp-amazon-eks/pull/147

Closing this ticket.
