### ISSUE TITLE
[Bug] Cannot build Platform team using builder construct

### ISSUE THREAD

**Issue by parkand1** [aws-quickstart/ssp-amazon-eks#271]
Platform Team cannot be instantiated correctly using a builder's approach. It extends ApplicationTeam, and its setup function call requires super() that cannot be done outside a constructor

**Comment by youngjeong46** [comment]
The Platform Team can be extended to form a new class (to abstract away complexity) in a separate directory structure to be imported and used. This resolves the constructor problem. Closing the issue now.
