### ISSUE TITLE
Python support via jsii

### ISSUE THREAD

**Issue by jpxd** [aws-quickstart/ssp-amazon-eks#285]
Hi, as far as I see this library works using a custom CDK construct.
Could support for other CDK languages like Python be added via jsii?
Most CDK constructs on http://constructs.dev support multiple languages.
This would open up the possibilities for a lot of developers!
Thanks!

**Comment by askulkarni2** [comment]
Hi @jpxd, thanks for the feedback. And we agree. We are tracking this in #98. Would you mind giving us a +1 on it? I will close this as a duplicate.

**Comment by jpxd** [comment]
Thanks four your answer, I didn't see the other issue. Gave a thumbs up there 👍🏻
