### ISSUE TITLE
Design - Workload Deployment Destination Configuration

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#30]
As a developer, I need to be able to specify via configuration in the App of Apps repo where my application will run (i.e. on which clusters).

**Comment by askulkarni2** [comment]
Just as a data point,`git@github.com:acme/inventory-service-cd.git path: dev, staging, prod` is the approach at Intuit. It works well for them. Once they self-on-boarded they would get all the environments with repos and deployment scafolding pre-configured. Its a neat approach, no tickets, no manual intervention.

**Comment by kcoleman731** [comment]
@shapirov103 let's discuss on sync.

**Comment by kcoleman731** [comment]
Discussed on 06/16 

We will go with @askulkarni2 approach. In each application repo, there will be an `infra` directory which will contain subdirectories for each env (e.g. `dev`, `test`, `prod`). Each subdir will contain k8s manifests for each env. 

Additionally, the app of apps repo will contain subdirs for each env as well.

**Comment by kcoleman731** [comment]
This is done.
