### ISSUE TITLE
Auto-sync all Apps in App of Apps repo

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#42]
As a developer, if I run `argocd app sync`, all apps should sync, not just the top level app of apps. 

Per @shapirov103 we can enable this via a `autoSync` flag in ArgoCD config

https://argoproj.github.io/argo-cd/user-guide/auto_sync/

**Comment by askulkarni2** [comment]
All that was needed for all apps to sync when executing `argocd app sync` was a fix in the namespace, see https://github.com/shapirov103/argo-apps/pull/1. 

If we want to decouple the sync of apps from the argo api server then we can introduce the autoSync in the top level app configuration.

**Comment by kcoleman731** [comment]
This is done.
