### ISSUE TITLE
Expand Nginx Addon

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#70]
To allow customers to save cost and eliminate complexity, each blueprint cluster will only leverage a single load balance. The load balancer will direct traffic to Nginx running in the cluster which will serve as a reverse proxy and forward requests to the appropriate service. The load balancer will be responsible for terminating TLS as well which will give all services running in the cluster TLS out of the box. A big win for customers. We need to enable this functionality via the Nginx addon.

@shapirov103 this one is likely going to fall in your court. We are going to need to think through how customers will be able to supply a custom domain to us. For instance, if I own a cluster in us-west-1, it is a "dev" cluster, and is running a workload called payments, I might want a url that looks like https://payments.dev.us-west-1.coleman.com How do we offer this functionality out the of box?

As part of this ticket, we will also need to:
[ ] document how all of this works
[ ] Add sample ingress objects to actual sample workloads.

Other references

https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/

**Comment by shapirov103** [comment]
We need to balance with the SaaS approach. For example, we could have a wildcard cert and use workload (or team) name in DNS name like you showed, e.g.  https://<workload>.<stage>.<region>.<org>.com. However, this does not work for the SaaS multi-tenancy (which I assume many will need). In such a case, the tenant name should be part of the DNS, e.g.

https://<tenant>.<workload>.<stage>.<region>.<org>.com. If we do that we can absorb the SaaS factory solution as well.  Although a little verbose. 

Also for prod, most customers will prefer not to have the stage in the URL for production. Also we should drop region and use Route53 geo proximity routing policy behind the scenes.  So

https://<tenant>.<workload/subdomain>.<org>.com (for prod)

**Comment by kcoleman731** [comment]
Whats the LOE between SaaS v non-SaaS. If not high, let's go with the SaaS approach. If high, we can probably skip for now?
